#!/bin/bash
shopt -s extglob
#Find maximum
max=1
for filename in ../[0-9][0-9][0-9][1-9]@(.jpg|.png); do
	temp=$(sed 's/^.*\/0*\([1-9]*[0-9]\)\..*$/\1/' <<< "$filename")
	if ((max<temp));
	then
		max=$temp
	fi
done
# Rename 
for filename in ../!([0-9][0-9][0-9][0-9])@(.jpg|.png); do
	ext=$(sed 's/^\.\.\/.*\(\..*\)$/\1/' <<< "$filename")
	if ((max < 99));
	then
		mv $filename "../00$((++max))$ext"
	elif ((max < 999));
	then
		mv $filename "../0$((++max))$ext"
	fi
done

for ((i=1; i<max; i++)); do
	digit=$(printf "%04d" $i)
	if [ -e ../$digit.png ] || [ -e ../$digit.jpg ];
	then
		continue
	else
		filename=$(ls -r ../*@(.jpg|.png) | head -n 1)
		ext=$(sed 's/^\.\.\/.*\(\..*\)$/\1/' <<< "$filename")
		((max--))
		mv $filename ../$digit$ext
	fi
done
